### ISSUE TITLE
TextProcessorWorker

### ISSUE THREAD

**Issue by Ebaa-Alnazer** [F7502/textprocessor-worker#1]
Hello, 
i was trying to run the program using ActiveMQ but each time i type (java -jar TextProcessorWorker.jar worker1.properties) in cmd ,it said that unable to access jar file .
I tried to move it to another directory but it's still give me the same error .So what is the problem here? @F7502 
Thank you in advance :)

**Comment by F7502** [comment]
Hi,
did you built the jar file using maven?
`mvn clean install`
This should create a file named `QueueTextProcessor-0.0.1-SNAPSHOT.jar` in the `/target` folder of the project. Copy that file (or the properties file) so that the jar and the `worker.properties` (this one is configured for ActiveMQ) are in the same folder. Then try to run it again from that folder:
`java -jar QueueTextProcessor-0.0.1-SNAPSHOT.jar worker.properties`
Does it work now?

**Comment by F7502** [comment]
ahh, sorry, my fault...

I committed a fix. Please pull the latest version fom GitHub and then try to run it as follows from the project root directory:
`mvn clean package`
`java -jar target\worker-jar-with-dependencies.jar worker.properties`

(on linux, replace `\` with `/` in the path to the jar file)

Is it working now?

**Comment by Ebaa-Alnazer** [comment]
yes, it's working now .
Thank you :)):)
